import os

DATA_DIR = r"/path/to/your/data/directory"

EXCHANGE_RATES = os.path.join(DATA_DIR, "ExchangeRates.xlsx")
BANKS_DUPLICATES = os.path.join(DATA_DIR, "BanksDoublesOther.xlsx")

HELSINKI_DIR = os.path.join(DATA_DIR, "Helsinki")
HELSINKI_MV = os.path.join(HELSINKI_DIR, "HelsinkiStocksMV.xlsx")
HELSINKI_MONTHLY_PRICES = os.path.join(HELSINKI_DIR, "HelsinkiMainListStocksPmontly.xlsx")
HELSINKI_MONTHLY_RETURNS = os.path.join(HELSINKI_DIR, "HelsinkiMainListStocksMontlyReturns.xlsx")
HELSINKI_WEEKLY_PRICES = os.path.join(HELSINKI_DIR, "HelsinkiMainListStocksPweekly.xlsx")
HELSINKI_WEEKLY_RETURNS = os.path.join(HELSINKI_DIR, "HelsinkiMainListStocksWeeklyReturns.xlsx")
HELSINKI_FIRST_NORTH = os.path.join(HELSINKI_DIR, "HelsinkiFirstNorth.xlsx")
HELSINKI_FINANCIALS = os.path.join(HELSINKI_DIR, "HelsinkiFinancials.xlsx")
HELSINKI_OUTPUT_MV = os.path.join(HELSINKI_DIR, "HelsinkiMainListStocksMV.xlsx")

COPENHAGEN_DIR = os.path.join(DATA_DIR, "Copenhagen")
COPENHAGEN_MV = os.path.join(COPENHAGEN_DIR, "CopenhagenStocksMV.xlsx")
COPENHAGEN_MV_EUR = os.path.join(COPENHAGEN_DIR, "CopenhagenMainListStocksMV_EUR.xlsx")
COPENHAGEN_MONTHLY_PRICES = os.path.join(COPENHAGEN_DIR, "CopenhagenStocksPMontly.xlsx")
COPENHAGEN_MONTHLY_PRICES_EUR = os.path.join(COPENHAGEN_DIR, "CopenhagenMainListStocksPMontly_EUR.xlsx")
COPENHAGEN_MONTHLY_RETURNS = os.path.join(COPENHAGEN_DIR, "CopenhagenMainListStocksMontlyReturnsEUR.xlsx")
COPENHAGEN_WEEKLY_PRICES = os.path.join(COPENHAGEN_DIR, "CopenhagenStocksPweekly.xlsx")
COPENHAGEN_WEEKLY_RETURNS = os.path.join(COPENHAGEN_DIR, "CopenhagenMainListStocksWeeklyReturns.xlsx")
COPENHAGEN_FIRST_NORTH = os.path.join(COPENHAGEN_DIR, "CopenhagenFirstNorth.xlsx")
COPENHAGEN_FINANCIALS = os.path.join(COPENHAGEN_DIR, "CopenhagenFinancials.xlsx")
COPENHAGEN_OUTPUT_MV = os.path.join(COPENHAGEN_DIR, "CopenhagenMainListStocksMV.xlsx")

OSLO_DIR = os.path.join(DATA_DIR, "Oslo")
OSLO_MV = os.path.join(OSLO_DIR, "OsloStocksMV.xlsx")
OSLO_MV_EUR = os.path.join(OSLO_DIR, "OsloMainListStocksMV_EUR.xlsx")
OSLO_MONTHLY_PRICES = os.path.join(OSLO_DIR, "OsloStocksPMontly.xlsx")
OSLO_MONTHLY_PRICES_EUR = os.path.join(OSLO_DIR, "OsloMainListStocksPMontly_EUR.xlsx")
OSLO_MONTHLY_RETURNS = os.path.join(OSLO_DIR, "OsloMainListStocksMontlyReturnsEUR.xlsx")
OSLO_WEEKLY_PRICES = os.path.join(OSLO_DIR, "OsloStocksPweekly.xlsx")
OSLO_WEEKLY_RETURNS = os.path.join(OSLO_DIR, "OsloMainListStocksWeeklyReturns.xlsx")
OSLO_GROWTH = os.path.join(OSLO_DIR, "OsloGrowth.xlsx")
OSLO_FINANCIALS = os.path.join(OSLO_DIR, "OsloFinancials.xlsx")
OSLO_OUTPUT_MV = os.path.join(OSLO_DIR, "OsloMainListStocksMV.xlsx")

STOCKHOLM_DIR = os.path.join(DATA_DIR, "Stockholm")
STOCKHOLM_MV = os.path.join(STOCKHOLM_DIR, "StockholmStocksMV.xlsx")
STOCKHOLM_MV_EUR = os.path.join(STOCKHOLM_DIR, "StockholmMainListStocksMV_EUR.xlsx")
STOCKHOLM_MONTHLY_PRICES = os.path.join(STOCKHOLM_DIR, "StockholmStocksPMontly.xlsx")
STOCKHOLM_MONTHLY_PRICES_EUR = os.path.join(STOCKHOLM_DIR, "StockholmMainListStocksPMontly_EUR.xlsx")
STOCKHOLM_MONTHLY_RETURNS = os.path.join(STOCKHOLM_DIR, "StockholmMainListStocksMontlyReturnsEUR.xlsx")
STOCKHOLM_WEEKLY_PRICES = os.path.join(STOCKHOLM_DIR, "StockholmStocksPweekly.xlsx")
STOCKHOLM_WEEKLY_RETURNS = os.path.join(STOCKHOLM_DIR, "StockholmMainListStocksWeeklyReturns.xlsx")
STOCKHOLM_FIRST_NORTH = os.path.join(STOCKHOLM_DIR, "StockholmFirstNorth.xlsx")
STOCKHOLM_FINANCIALS = os.path.join(STOCKHOLM_DIR, "StockholmFinancials.xlsx")
STOCKHOLM_OUTPUT_MV = os.path.join(STOCKHOLM_DIR, "StockholmMainListStocksMV.xlsx")
